import Home from "../../components/pages/Home";
import Layout from "../../components/common/layout";
import { useRouter } from "next/router";

export default function Index() {
  const router = useRouter();
  const { imageId } = router.query;
  return (
    <Layout
      title={`Orange - AI Art Search`}
      description="Search Images generated by Midjourney (Midjourney - An AI Art Generation model)."
    >
      <Home imageId={imageId?.toString()} />
    </Layout>
  );
}
