export default function getSurprisePrompt() {
  const a = [
    "some",
    "a bitter,",
    "the",
    "the time you met a",
    "a",
    "the death of a",
    "the other",
    "a former",
    "an evil,",
    "a surprisingly",
    "a small-town,",
    "a famous,",
    "an exceptionally",
    "a spy posing as a",
    "a hopelessly",
    "the secret life of a",
    "your cousin, the",
    "the downfall of a",
    "the dark side of a",
    "the special talent of a",
    "a friendly,",
    "a soon-to-be",
    "a cool,",
    "your run-in with a",
    "a nerdy,",
    "a car accident caused by a",
    "a futuristic",
    "your ancestor, the",
    "an unreliable,",
    "a political scandal featuring a",
    "a professional",
    "a PR nightmare caused by a",
    "an extremely",
    "trying to sell a car to a",
    "the hijinks of a",
    "a dangerously",
    "an undercover,",
    "the career failure of a",
    "the diary of a",
    "the magical journey of a",
    "an alien undercover as a",
    "someone you met in a haunted forest. They were a",
    "how you used to be a",
    "the ghost of a",
  ];

  const b = [
    "blonde",
    "hideous",
    "brave",
    "lazy",
    "clever",
    "mentally-unwell",
    "conniving",
    "party-going",
    "guilt-ridden",
    "forgetful",
    "rude",
    "camo-wearing",
    "casual",
    "basement-dwelling",
    "traumatized",
    "heartless",
    "house-bound",
    "cringey",
    "gifted",
    "homeless",
    "radical",
    "lost",
    "fashionable",
    "surprisingly wholesome",
    "elegant",
    "young",
    "polite",
    "terrified",
    "quiet",
    "skittish",
    "gay",
    "French",
    "republican",
    "well-read",
    "democratic",
    "methodical",
    "far-right",
    "drug-addicted",
    "far-left",
    "world-champion",
    "narcissistic",
    "stuck-in-the-past",
    "granola-munching",
    "bigoted",
    "social",
    "hypocritical",
    "confident",
    "cursed",
    "mentally-unstable",
    "possessed",
    "cowardly",
    "gunslinging",
    "sheepish",
    "constipated",
    "toxically optimistic",
    "reckless",
    "well-connected",
    "wounded",
    "rich",
    "picky",
    "poor",
    "magical",
    "gloomy",
    "toxic",
    "smug",
    "homely",
    "lucky",
    "cocky",
    "stinky",
    "FBI agent",
    "compassionate",
    "thief",
    "peaceful",
    "virtual-reality",
    "soft-spoken",
    "gorgeous",
    "workaholic",
    "goth",
    "old",
    "frantic",
    "grouchy",
    "wealthy",
    "stubborn",
    "suspicious",
    "bubbly",
  ];

  const c = [
    "bartender",
    "door-to-door vitamin seller",
    "engineer",
    "armored truck driver",
    "librarian",
    "soldier",
    "elementary school teacher",
    "lunch lady",
    "graphic designer",
    "superhero",
    "small business owner",
    "monster truck driver",
    "stay-at-home mom",
    "corn farmer",
    "nurse",
    "documentary producer",
    "dog trainer",
    "lifestyle blogger",
    "astronaut",
    "chef",
    "janitor",
    "celebrity agent",
    "guy",
    "cave diver",
    "gal",
    "lifeguard",
    "grandma",
    "social media addict",
    "grandpa",
    "father of nine girls",
    "pet hoarder",
    "koala breeder",
    "pilot",
    "exotic animal smuggler",
    "cynic",
    "politician",
    "olympic swimmer",
    "art student",
    "ballet teacher",
    "paramedic",
    "pianist",
    "hypochondriac",
    "detective",
    "forest nymph",
    "police officer",
    "cyclops",
    "construction worker",
    "wrestling champion",
    "intern",
    "Mars colonist",
    "college student",
    "tax collector",
    "mechanic",
    "wizard",
    "cosmetologist",
    "child prodigy",
    "author",
    "dragon slayer",
    "journalist",
    "elf",
    "assistant manager",
    "sorcerer",
    "grocery clerk",
    "troll",
    "priest",
    "humanoid robot",
    "IT specialist",
    "spaceship mechanic",
    "homeless man",
    "wormhole explorer",
    "secretary",
    "time traveler",
    "teenager",
    "cowgirl",
    "firefighter",
    "clown",
    "lawyer",
    "underwater basket weaver",
    "drug dealer",
    "centaur",
    "middle school teacher",
    "ticket taker",
    "programmer",
    "juror",
    "florist",
    "brain surgeon",
    "stay-at-home dad",
    "life coach",
    "singer-songwriter",
    "kidnapper",
    "movie star",
    "mail carrier",
    "runner",
    "train conductor",
    "serial killer",
    "retail employee",
    "door-to-door salesman",
    "talking horse",
    "football player",
    "shuttle driver",
    "comic strip author",
    "ancient god",
    "babysitter",
    "magician",
    "street vendor",
    "sewer troll",
  ];

  const d = [
    "hides from the police",
    "vandalizes a famous painting",
    "runs away from home",
    "forgets where they live",
    "has to find a new job",
    "gets stuck in a cardboard bailer",
    "never leaves their house",
    "drops out of a GED prep class",
    "gets out of jail",
    "joins a convent",
    "paints horrible modern art",
    "finds themselves in a sinking submarine",
    "moonlights as a parking attendant",
    "climbs Mount Everest every year",
    "buys a used school bus",
    "gets involved with a drug cartel",
    "starts selling stolen car parts",
    "refuses to listen to hip hop",
    "kills their neighbor",
    "starts a charity to cure smallpox",
    "adopts a 15-year-old from Alaska",
    "fakes their own death",
    "throws away their life savings",
    "robs a grocery store",
    "eats only bananas for a month",
    "comes back to life",
    "is trapped in a box",
    "tries to sneak onto an evacuation rocket",
    "goes to community college",
    "switches bodies with their dad",
    "gets in a fight in a mysterious van",
    "is cursed to say everything on their mind",
    "gives advice to at-risk teens",
    "tries to escape the afterlife",
    "has to memorize the Bible",
    "learns how to talk to animals",
    "reports their spouse as missing",
    "has to convince their neighbor their house is haunted",
    "starts a job making potato chips",
    "gets caught in an awkward love triangle",
    "finds their true love",
    "falls into a vat of baked beans",
    "forms an addiction to simple syrup",
    "forms an addiction to online shopping",
    "builds houses for the homeless",
    "turns into a mythical creature",
    "starts eating paper clips",
    "runs a money-laundering scheme",
    "gets stuck in a closet at work",
    "sells their soul in the classifieds",
    "invents a cure to a disease",
    "hijacks a public bus",
    "finds a secret hidden treasure",
    "falls in love with their enemy’s daughter",
    "rents a minivan",
    "finds irrefutable evidence of alien life",
    "hires 20 underage employees",
    "becomes a stand-up comedian",
    "joins a civil rights campaign",
    "convinces people they have magic powers",
    "has to flee the country",
    "gets revenge on an old romantic partner",
    "starts a plague",
    "turns an old closet into an interdimensional portal",
    "sneaks into a cereal factory",
    "gets in a fight with a cashier",
    "adopts eight kittens",
    "discovers their enemy turned them into a rabbit",
    "knits sweaters laced with poison",
    "lives the plot of a Dr. Seuss book",
    "is in the most dangerous city in the world",
    "wakes up locked in a high school bathroom",
    "finds a buried ancient society",
    "hires a rocket to the moon",
    "impersonates a famous musician",
    "sues the pizza delivery company",
    "impulsively starts the wave at sport games",
    "lives an entire day in reverse",
    "surprises their spouse with a dead mouse",
    "sells horrible poetry on public transit",
    "joins a 10-piece brass band",
    "buries an enormous sum of money",
    "sells their soul to a jewelry store",
    "spends a week inside a Taco Bell refrigerator",
    "asks a clown on a date",
    "throws a dead body in a lake",
    "is pretending to be a robot",
    "tries to visit Obama at his home",
    "joins an extreme religious cult",
    "sets six gerbils free in a park",
  ];

  const e = [
    "to save money",
    "to fix their bad credit score",
    "because of a dark past",
    "after discovering an enchanted orb",
    "because of a secret terrorist plot",
    "… until an evil power changes everything",
    "because there was an alien invasion",
    "because of scheduling conflicts",
    "thanks to childhood trauma",
    "to save their worst enemy’s life",
    "to impress their dead parents",
    "as an elaborate ploy to make friends",
    "because of a bet placed years ago",
    "despite everyone telling them not to",
    "out of an abundance of caution",
    "as an extreme form of method acting",
    "while avoiding a suspicious-looking gentleman",
    "to stall a court hearing",
    "in an effort to pay off a debt",
    "after looking themselves up online",
    "without consulting their therapist",
    "but the narrator gets some of the details wrong",
    "because their best friend is evil",
    "after drinking a funny looking soda",
    "with ulterior motives",
    "to win back their true love",
    "after winning the lottery",
    "as a political stunt",
    "under suspicious circumstances",
    "to get intelligence for a foreign military",
    "with the help of an imaginary friend",
    "with the help of off-brand energy drinks",
    "for charity",
    "and blames it on a mid-life crisis",
    "for a tax write-off",
    "because nobody would take them seriously otherwise",
    "even though they have a cold",
    "to prevent an ancient prophecy from being fulfilled",
    "despite their spouse telling them not to",
    "to have something interesting for their memoir",
    "despite their dreams of being a polar bear",
    "in an obscure village in central Brazil",
    "without getting caught",
    "as a form of protest",
    "to impress their crush",
    "to rebel against societal norms",
    "while listening to 90s rap music",
    "without realizing they are being followed",
    "due to undiagnosed mental conditions",
    "and has to explain it to a judge",
    "after hitting their head on a filing cabinet",
    "due to an interplanetary disturbance",
    "while screaming obscenities",
    "to disguise their true magic powers",
    "in a moment of weakness",
    "to hide from the mafia",
    "to pass a high-school class from years ago",
  ];

  var i0 = a[~~(Math.random() * a.length)];
  var i1 = b[~~(Math.random() * b.length)];
  var i2 = c[~~(Math.random() * c.length)];
  var i3 = d[~~(Math.random() * d.length)];
  var i4 = e[~~(Math.random() * e.length)];

  var outstring =
    "Write a story about " + i0 + " " + i1 + " " + i2 + " who " + i3 + " " + i4;
  return outstring;
}
