import Home from '../components/pages/Home'
import Layout from '../components/common/layout'

export default function Index () {
  return (
    <Layout
      title={`Picsy - AI Art Search`}
      description="Pics contains more than 6 million images generated by Image Generative AI - Midjourney. Picsy lets you search among these 6 million images for different use cases. Picsy allows you to download these images for general purposes like Analysis, Education and Personal Experiance"
    >
      <Home />
    </Layout>
  )
}
