import Home from '../components/pages/Home'
import Layout from '../components/common/layout'

export default function Index () {
  return (
    <Layout
      title={`Orange - AI Art Search`}
      description="Search Images generated by Midjourney (Midjourney - An AI Art Generation model)."
    >
      <Home />
    </Layout>
  )
}
